epochs: 10
eval_steps: 20
log_steps: 10
seed: 42
lr: 0.0001
bert_lr: 0.00001
batch_size: 8
ignore_none_rel: False
train_split: 0.8
test_split: 0.1
val_split: 0.1
max_length: 510
data_path: "" # INSERT LOCAL DATA PATH
label_map: 
    before: 0
    start: 1
    "on": 2
    stop: 3
    after: 4
    uncertain: 5
    no_intake: 6

